#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────────────────────
# restructure-repo.sh
#
# One-time script to move FF-Content-Writer out of ~/.git (where the git root
# is the home folder) into its own self-contained repo whose root IS the
# project folder. Safer than restructuring in place: it builds a fresh repo
# in a sibling staging folder, force-pushes that, and leaves the old ~/.git
# untouched until you confirm everything works.
#
# Usage:  bash restructure-repo.sh
#
# What it does NOT do:
#   - touch ~/.git (your existing repo stays intact as a rollback)
#   - delete or rename your current project folder
#   - push without showing you what's about to be pushed
# ──────────────────────────────────────────────────────────────────────────────

set -euo pipefail

CURRENT_PROJECT="$HOME/Desktop/GitHub FF/FF-Content-Writer"
STAGING="$HOME/Desktop/ff-content-writer-new"
WORKFLOW_SRC="$HOME/.github/workflows/deploy.yml"
REMOTE_NAME="ff-content-writer"
BRANCH="main"

bold()    { printf "\033[1m%s\033[0m\n" "$*"; }
green()   { printf "\033[32m%s\033[0m\n" "$*"; }
yellow()  { printf "\033[33m%s\033[0m\n" "$*"; }
red()     { printf "\033[31m%s\033[0m\n" "$*"; }
divider() { printf '%s\n' "────────────────────────────────────────────────────────────"; }

confirm() {
  local prompt="${1:-Continue?}"
  read -r -p "$prompt [y/N] " ans
  [[ "$ans" =~ ^[Yy]$ ]]
}

# ── 0. Sanity checks ──────────────────────────────────────────────────────────
divider
bold "Step 0 — checking preconditions"

[ -d "$CURRENT_PROJECT" ] || { red "Project folder missing: $CURRENT_PROJECT"; exit 1; }
[ -f "$WORKFLOW_SRC" ]    || { red "Workflow file missing: $WORKFLOW_SRC"; exit 1; }
[ -d "$HOME/.git" ]       || { red "No git repo at \$HOME — nothing to migrate."; exit 1; }

if [ -e "$STAGING" ]; then
  red "Staging folder already exists: $STAGING"
  red "Remove or rename it first, then re-run."
  exit 1
fi

# We only care that the PROJECT folder is clean — the whole point of the
# restructure is to walk away from everything else $HOME's git tracks.
PROJECT_REL="Desktop/GitHub FF/FF-Content-Writer"
if ! git -C "$HOME" diff --quiet -- "$PROJECT_REL" \
  || ! git -C "$HOME" diff --cached --quiet -- "$PROJECT_REL"; then
  yellow "The project folder has uncommitted changes."
  yellow "Run from your terminal:"
  echo
  echo "  cd ~"
  echo "  git status --short -- \"$PROJECT_REL\""
  echo "  git add \"$PROJECT_REL\""
  echo "  git commit -m \"Pre-restructure: capture project changes\""
  echo
  yellow "Then re-run this script. (Anything outside the project folder is"
  yellow "ignored — the restructure abandons it on purpose.)"
  exit 1
fi

# Pull remote URL from your existing repo so we don't have to guess.
REMOTE_URL="$(git -C "$HOME" remote get-url "$REMOTE_NAME" 2>/dev/null || true)"
[ -n "$REMOTE_URL" ] || { red "Remote '$REMOTE_NAME' not found at \$HOME."; exit 1; }

green "Project folder:   $CURRENT_PROJECT"
green "Workflow source:  $WORKFLOW_SRC"
green "Staging target:   $STAGING"
green "Remote URL:       $REMOTE_URL"

# ── 1. Build staging folder ───────────────────────────────────────────────────
divider
bold "Step 1 — building staging folder"

mkdir -p "$STAGING"
# rsync preserves attrs and skips macOS junk. Excludes:
#   - .git: would shadow the fresh repo we're about to init
#   - .DS_Store: macOS junk
#   - node_modules / dist: build artifacts, regenerated by deploy
#   - .env*, *.rtf: secrets / credentials — must NOT land in public repo
#   - .claude*, .swarm, .mcp.json: local agent/IDE state
rsync -a \
  --exclude='.git' \
  --exclude='.DS_Store' \
  --exclude='node_modules' \
  --exclude='dist' \
  --exclude='.env' \
  --exclude='.env.*' \
  --exclude='*.rtf' \
  --exclude='.claude' \
  --exclude='.claude-flow' \
  --exclude='.swarm' \
  --exclude='.mcp.json' \
  "$CURRENT_PROJECT/" "$STAGING/"

# Write a .gitignore so anything we missed (or future local state) stays out.
cat >"$STAGING/.gitignore" <<'GITIGNORE'
# Dependencies
node_modules/

# Build output
dist/

# Local env / secrets — NEVER commit
.env
.env.*
*.rtf

# Editor / OS
.DS_Store
.vscode/
.idea/

# Local agent / IDE state
.claude/
.claude-flow/
.swarm/
.mcp.json

# Logs
*.log
npm-debug.log*
GITIGNORE

# Write a fresh workflow at the new repo root (paths root-relative, not nested).
mkdir -p "$STAGING/.github/workflows"
cat >"$STAGING/.github/workflows/deploy.yml" <<'WORKFLOW'
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        env:
          # VITE_ vars are inlined into the client bundle at build time —
          # treat as public. Set in GitHub repo Settings → Secrets.
          VITE_ANTHROPIC_KEY: ${{ secrets.VITE_ANTHROPIC_KEY }}
        run: npm run build

      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
WORKFLOW

green "Copied project files + wrote .gitignore + root-relative workflow into $STAGING"

# ── 2. Initialize fresh repo ──────────────────────────────────────────────────
divider
bold "Step 2 — initializing fresh git repo"

cd "$STAGING"
git init -b "$BRANCH" >/dev/null
git add -A
# Use whatever git identity is configured globally — no hardcoded overrides.
git commit -m "Restructure: project folder is now repo root" >/dev/null
git remote add "$REMOTE_NAME" "$REMOTE_URL"

green "Fresh repo initialized at $STAGING"
echo
bold "Files in the new commit:"
git ls-files | sed 's/^/  /' | head -40
TOTAL=$(git ls-files | wc -l | tr -d ' ')
echo "  … ($TOTAL files total)"

# ── 3. Confirm before pushing ─────────────────────────────────────────────────
divider
bold "Step 3 — ready to force-push"
echo
yellow "About to run:"
echo "  git push --force-with-lease $REMOTE_NAME $BRANCH"
echo
yellow "This rewrites the remote 'main' branch."
yellow "Your existing ~/.git is untouched — you can roll back by re-pushing from there."
echo
confirm "Push now?" || { yellow "Stopped before push. Staging folder kept at $STAGING for inspection."; exit 0; }

git push --force-with-lease "$REMOTE_NAME" "$BRANCH"

# ── 4. Watch the deploy ───────────────────────────────────────────────────────
divider
bold "Step 4 — watching GitHub Actions"

if command -v gh >/dev/null 2>&1; then
  # Wait a moment for the run to register, then watch the latest one.
  sleep 3
  gh run watch --exit-status || red "Deploy run failed — check Actions tab."
else
  yellow "gh CLI not installed. Check the run at:"
  echo "  https://github.com/$(echo "$REMOTE_URL" | sed -E 's#.*[:/]([^/]+/[^/.]+)(\.git)?$#\1#')/actions"
fi

# ── 5. Next steps ─────────────────────────────────────────────────────────────
divider
bold "Done."
echo
green "Once the deploy is green, finalize the cutover:"
cat <<EOF

  # Move the new repo into place (keeps the old folder as a backup):
  mv "$CURRENT_PROJECT" "${CURRENT_PROJECT}.bak"
  mv "$STAGING" "$CURRENT_PROJECT"

  # Verify Cowork still mounts the same path — it should.
  # Then, when you're confident, clean up the old top-level repo:
  rm -rf "\$HOME/.git" "\$HOME/.github"

  # And reinstall deps inside the new folder:
  cd "$CURRENT_PROJECT" && npm install

EOF
